name: CrazyStaff
authors: [Ryder Belserion]
main: com.badbones.CrazyStaff
api-version: '1.13'
version: 'v1.0.2'
description: 'A simple staff plugin'
load: POSTWORLD
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.0