name: CrazyStaff
authors: [Ryder Belserion]
main: com.badbones.CrazyStaff
api-version: '1.13'
version: '1.4-STABLE'
description: 'A simple staff plugin'
load: POSTWORLD
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.0