name: Build
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Build
        run: ./gradlew build --stacktrace
      - name: Cache
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/cache
    # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-primes
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Crazy-Staff
          path: build/libs/Crazy-Staff-*.*.*.jar
